# Generated by Django 3.0.8 on 2022-07-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220712_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='movile_no',
            new_name='mobile_no',
        ),
    ]
