# Generated by Django 3.0.8 on 2022-05-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caterers',
            new_name='enquire',
        ),
    ]
