# Generated by Django 3.0.8 on 2022-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0002_auto_20220521_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
