# Generated by Django 3.0.8 on 2022-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0003_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile', models.IntegerField()),
                ('services', models.CharField(choices=[('ECA', 'ECA'), ('Direct Taxation Advice', 'Direct Taxation Advice'), ('ITR Filling', 'ITR Filling'), ('File Revised Return', 'File Revised Return'), ('Company Formation', 'Company Formation'), ('Registration and Formation of LLPs', 'Registration and Formation of LLPs'), ('Company Formation', 'Company Formation')], max_length=50)),
            ],
        ),
    ]
