# Generated by Django 3.0.8 on 2022-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0005_auto_20220606_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_llp_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile', models.IntegerField()),
                ('Book_keeping_and_accountancy', models.IntegerField()),
                ('Finalisation_of_accounts_books', models.IntegerField()),
                ('All_other_MCA_compliances', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='direct_taxcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile', models.IntegerField()),
                ('Registration_on_portal', models.BooleanField()),
                ('Income_Tax_Return_Filings', models.BooleanField()),
                ('Income_Tax_Audit_filings', models.BooleanField()),
                ('Assesment_filings', models.BooleanField()),
                ('Tax_planning', models.BooleanField()),
                ('Advice_Consultancy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='indirect_taxcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile', models.IntegerField()),
                ('Registration_on_portal', models.BooleanField()),
                ('Tax_planning', models.BooleanField()),
                ('Advice_Consultancy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='virtual_book_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile', models.IntegerField()),
                ('Name_approval_application', models.BooleanField()),
                ('Company_LLP_registration', models.BooleanField()),
                ('All_other_MCA_compliances', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
