# Generated by Django 3.0.8 on 2022-07-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0006_auto_20220702_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_llp_questions',
            name='Book_keeping_and_accountancy',
        ),
        migrations.RemoveField(
            model_name='company_llp_questions',
            name='Finalisation_of_accounts_books',
        ),
        migrations.RemoveField(
            model_name='virtual_book_questions',
            name='Company_LLP_registration',
        ),
        migrations.RemoveField(
            model_name='virtual_book_questions',
            name='Name_approval_application',
        ),
        migrations.AddField(
            model_name='company_llp_questions',
            name='Company_LLP_registration',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_llp_questions',
            name='Name_approval_application',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtual_book_questions',
            name='Book_keeping_and_accountancy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtual_book_questions',
            name='Finalisation_of_accounts_books',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_llp_questions',
            name='All_other_MCA_compliances',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='virtual_book_questions',
            name='All_other_MCA_compliances',
            field=models.IntegerField(),
        ),
    ]
