# Generated by Django 3.0.8 on 2022-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0007_auto_20220702_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual_book_questions',
            name='All_other_MCA_compliances',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='virtual_book_questions',
            name='Book_keeping_and_accountancy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='virtual_book_questions',
            name='Finalisation_of_accounts_books',
            field=models.BooleanField(),
        ),
    ]
