# Generated by Django 3.0.8 on 2022-07-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0008_auto_20220702_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtual_book_questions',
            old_name='All_other_MCA_compliances',
            new_name='MIS_reports_Receivables_Ageing_report',
        ),
    ]
