# Generated by Django 3.0.8 on 2022-07-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0009_auto_20220712_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
