# Generated by Django 3.0.8 on 2022-07-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0011_auto_20220713_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_yourself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unlock_eca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
