# Generated by Django 3.0.8 on 2022-07-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0012_auto_20220713_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_yourself',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unlock_eca',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
