# Generated by Django 3.0.8 on 2022-07-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0014_auto_20220718_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_llp_questions',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='direct_taxcation',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indirect_taxcation',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='refund_status',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='virtual_book_questions',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
