# Generated by Django 3.0.8 on 2022-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0015_auto_20220719_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_llp_questions',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direct_taxcation',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indirect_taxcation',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtual_book_questions',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
