# Generated by Django 3.0.8 on 2022-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0018_auto_20220719_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_llp_questions',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direct_taxcation',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indirect_taxcation',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='virtual_book_questions',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Reschedule', 'Reschedule')], max_length=50, null=True),
        ),
    ]
