# Generated by Django 3.0.8 on 2022-07-20 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax2win', '0019_auto_20220719_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices_enquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('plan', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('MultipleF-16', 'MultipleF-16'), ('Business Income', 'Business Income'), ('Capital Gain', 'Capital Gain')], max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
