# Generated by Django 3.0.8 on 2022-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax2win', '0020_prices_enquire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
